import json, pathlib
from overlord_worldsim.canon.parse import parse_source
from overlord_worldsim.canon.enrich_model import EnrichmentBatch
from overlord_worldsim.canon.enrich_registry import load_enrichment_batches, load_entity_registry
from overlord_worldsim.canon.enrich_verifier import verify_enrichment

raw = pathlib.Path("data/raw/无职转生TXT合集.txt").read_text(encoding="utf-8")
doc = parse_source(raw)
v16_chunks = [c for c in doc.chunks if c.volume_no==16]
idxs = [0,1,2,5,6,8,10,12,13,15,18,22,25,30,35,40,45,50,55,60,65,70,80,85,90,95]
picked = [v16_chunks[i] for i in idxs if i < len(v16_chunks)]
notes_en = [
    "Opening recap: Rudeus as Orsted subordinate and Eris marriage, first mission framing",
    "Orsted reviews future diary and presses for full 10 human-god contacts",
    "Five dragon generals and treasures: Kaos part recovered, Laplace in 80 years",
    "Doristina vs Darius kidnapping pretext usable as censure",
    "One-month mission: win Perugius for Ariel",
    "Summon circle from Orsted tested before family, Roxy fetches staff",
    "First summon misfires to Arumanfi, second with greatest beast image yields Leo",
    "Leo imprints: licks hand then pounces on Roxy, oath sworn",
    "Two days of Leo: collar, kennel, gate guard, patrol, comfort Lucy, escort Norn",
    "Luke ambushes at door courting Eris, knocked out, flagged as apostle candidate",
    "Luke plea: six-year network lacks Perugius decisive backing",
    "Human god limit three, Orsted fought Sword God North God Demon King proof",
    "Rudeus explains to Sylphy: queen-making is century-scale layout for Orsted",
    "Garden tea party: Ariel off-mode, Seven Stars evasive",
    "Orsted tea with Seven Stars, Sylvaril spill no anger, Ariel notes tolerance",
    "Ariel cites play line holder of unfitting power perish and doubts queenship",
    "Perugius generous thesis: lone worry is conceit, stretch and slap reset",
    "Rudeus reports Cavani to Orsted, receives book cover as fallback answer",
    "Saurus death as anti-Boreas vs first prince intrigue unsolved",
    "Transfer dizziness like human-god dream, newcomers stunned",
    "Outer stacks ~300 years post war, 4km walk outer ring off centre",
    "Derrick diary: bat crest, Ariel shock-identified as key proof",
    "Melee: Frost Nova slow, rock cannon vs snail, Luke covers Ariel",
    "Audience hall twelve spirits, Perugius endorses despite imperfect answer, orders transfer prep",
    "Third hut meeting: Darius and Luke fixed as apostles, Ariel uncontrollable",
    "Pre-expedition boys meet: barrier tale, low-cost armor for future fight",
]
evidence = []
for i, ch in enumerate(picked):
    evidence.append({
        "evidence_id": f"EV160{i+1:02d}",
        "volume_no": 16,
        "unit_id": ch.unit_id,
        "chapter_title": ch.chapter_title,
        "source_start_line": ch.source_start_line,
        "source_end_line": ch.source_end_line,
        "evidence_type": "CANON_EXPLICIT",
        "confidence": "EXPLICIT",
        "note": notes_en[i]
    })

def ev(*ns): return [f"EV160{n:02d}" for n in ns]

# Build full batch dict matching EnrichmentBatch.to_json shape
batch = {
    "batch_id": "ENRICH_V016",
    "source_volume": 16,
    "source_unit_ids": ["U0283","U0284","U0285","U0286","U0287","U0288","U0289","U0290","U0291","U0292","U0293","U0294","U0295","U0296","U0297"],
    "schema_version": "1.0.0",
    "evidence": evidence,
    "character_profiles": [
        {
            "profile_id": "CP16001","character_id": "E0001","phase_id": "P16001","phase_name": "Orsted subordinate early","start_date": None,"end_date": None,"date_precision": "UNKNOWN","age_description": "~18, Sharia husband, new subordinate",
            "personality_traits": ["cautious","family-first","responsible","curious"],"values": ["protect family","serve Orsted","live earnestly"],"desires": ["secure home","win Perugius"],"fears": ["human god re-control","curse misjudgment"],"taboos": ["over-hide from family"],"insecurities": ["misspeak to Orsted"],"pride": "great magic","impulsiveness": "LOW","patience": "HIGH","risk_tolerance": "MEDIUM","self_control": "HIGH","attachment_style": "attached to wives and sisters","authority_attitude": "reverent to Orsted, polite to Perugius","family_attitude": "extends family via beast","romantic_attitude": "married three, cherishes bonds","violence_attitude": "avoid killing, rock cannon if needed","money_attitude": "Sharia-funded","status_attitude": "seeks allies not titles","race_attitude": "treats beast and spirits as peers","religious_attitude": "none","loyalty": "HIGH","ambition": "MODERATE","short_term_goals": ["summon guardian","win Perugius","retrieve diary"],"long_term_goals": ["help Orsted in a century"],"obligations": ["first mission","guardian pact"],"decision_tendencies": ["report then consult Sylphy","prove with books"],"speech_tendencies": ["report register to lord","frank to family"],"social_tendencies": ["careful go-between at fort"],"conflict_tendencies": ["diplomacy over force"],"known_skills": ["chantless multi-magic","summoning","rock cannon"],"knowledge_state": ["10 contacts","treasures and dragon generals","Derrick-Cavani link"],"relationship_tendencies": ["wary of Luke","ally to Ariel without flaunting"],"behavior_changes_note": "shifts to network building","summary": "Rudeus bridges home and kingship with beast and books","visible_from_volume": 16,"visible_to_volume": None,"evidence_refs": ev(6,7,8,12,22)
        },
        {
            "profile_id": "CP16002","character_id": "E0044","phase_id": "P16002","phase_name": "Fort waiting","start_date": None,"end_date": None,"date_precision": "UNKNOWN","age_description": "~16-17, second princess in exile",
            "personality_traits": ["resilient","clever","flexible","performative"],"values": ["elegant rule via performance","talent is network"],"desires": ["gain Perugius","honor 13 retainers"],"fears": ["judged unfit","lose more"],"taboos": ["show weakness long"],"insecurities": ["doubts queenship"],"pride": "royal etiquette and eye for people","impulsiveness": "MEDIUM","patience": "MEDIUM","risk_tolerance": "MEDIUM","self_control": "HIGH","attachment_style": "trusts Sylphy Luke deeply","authority_attitude": "negotiates with Perugius","family_attitude": "opposes brothers","romantic_attitude": "with Luke as lord-retainer","violence_attitude": "delegates combat","money_attitude": "trades favors","status_attitude": "kingship as duty","race_attitude": "accepts spirits and beast","religious_attitude": "none","loyalty": "HIGH","ambition": "HIGH","short_term_goals": ["answer king element","mend with dragon king","secure transfer"],"long_term_goals": ["ascend throne"],"obligations": ["memory of 13"],"decision_tendencies": ["hear full stories then decide","ease with tea"],"speech_tendencies": ["public formal","private self-mocking"],"social_tendencies": ["garden tea upkeep"],"conflict_tendencies": ["answer trial with etiquette"],"known_skills": ["statecraft","recruitment"],"knowledge_state": ["Doristina leverage","friends around Cavani"],"relationship_tendencies": ["from testing to trust with Rudeus","pillars with Luke Sylphy"],"behavior_changes_note": "from shutdown to answer via history","summary": "Ariel rediscovers kingship and wins dragon king","visible_from_volume": 16,"visible_to_volume": None,"evidence_refs": ev(14,15,16,17,22,24)
        },
        {
            "profile_id": "CP16003","character_id": "E0006","phase_id": "P16003","phase_name": "Guard and wife","start_date": None,"end_date": None,"date_precision": "UNKNOWN","age_description": "late teens, guard and first wife, mother of Lucy",
            "personality_traits": ["gentle","firm","loyal","sharp"],"values": ["both friends and family","honesty and guard"],"desires": ["help Ariel safe","be trusted"],"fears": ["branded traitor","Luke hurt"],"taboos": ["abandon friends"],"insecurities": ["torn between camps"],"pride": "precise coordination","impulsiveness": "LOW","patience": "HIGH","risk_tolerance": "MEDIUM","self_control": "HIGH","attachment_style": "dual loyalty to Rudeus and Ariel","authority_attitude": "respects Ariel and Orsted","family_attitude": "puts Lucy first","romantic_attitude": "loves Rudeus","violence_attitude": "cover with wind","money_attitude": "none","status_attitude": "judges not by rank","race_attitude": "accepts all","religious_attitude": "none","loyalty": "HIGH","ambition": "MODERATE","short_term_goals": ["swap front/back in labyrinth","persuade Eris to rotate"],"long_term_goals": ["be model mother-guard"],"obligations": ["guard oath","mother duty"],"decision_tendencies": ["sync with glance","soothe then reason"],"speech_tendencies": ["short echo to Rudeus","polite guard to Ariel"],"social_tendencies": ["frank in women meet"],"conflict_tendencies": ["cover not duel"],"known_skills": ["wind and heal support","wordless sync"],"knowledge_state": ["curse bias","transfer taboo"],"relationship_tendencies": ["rotate aid with Eris","complement Luke"],"behavior_changes_note": "from worry to bridge","summary": "Sylphy balances friend and family with silent sync","visible_from_volume": 16,"visible_to_volume": None,"evidence_refs": ev(13,17,23)
        },
        {
            "profile_id": "CP16004","character_id": "E0029","phase_id": "P16004","phase_name": "Fort dragon king","start_date": None,"end_date": None,"date_precision": "UNKNOWN","age_description": "dragon king, master of twelve spirits",
            "personality_traits": ["proud","just","testing","generous"],"values": ["friends and faith","king inherits nameless will"],"desires": ["find worthy king","continue vs Laplace"],"fears": ["entrust wrongly"],"taboos": ["disrespect trial"],"insecurities": ["not yielding even to Orsted"],"pride": "name Perugius and voice over Asura","impulsiveness": "LOW","patience": "MEDIUM","risk_tolerance": "LOW","self_control": "HIGH","attachment_style": "chooses master by trial","authority_attitude": "is authority","family_attitude": "spirits as kin","romantic_attitude": "none","violence_attitude": "wield via presence and circles","money_attitude": "none","status_attitude": "judges by caliber","race_attitude": "rules spirits","religious_attitude": "none","loyalty": "HIGH","ambition": "LOW","short_term_goals": ["test king element","ready transfer"],"long_term_goals": ["stable Asura via king"],"obligations": ["seven heroes legacy"],"decision_tendencies": ["judge by caliber beyond correct answer"],"speech_tendencies": ["proclaiming archaic"],"social_tendencies": ["adjudicate among twelve"],"conflict_tendencies": ["settle by Q&A"],"known_skills": ["circle craft","fort rule"],"knowledge_state": ["knows human-god, wary","knows Cavani friends"],"relationship_tendencies": ["from cold to aide to Ariel","tests Rudeus as outside aid"],"behavior_changes_note": "from silence to endorsement","summary": "Testing dragon king becomes Ariel strongest backer","visible_from_volume": 16,"visible_to_volume": None,"evidence_refs": ev(18,22,24)
        },
        {
            "profile_id": "CP16005","character_id": "E0021","phase_id": "P16005","phase_name": "Escort","start_date": None,"end_date": None,"date_precision": "UNKNOWN","age_description": "Mad Sword King, third wife, multi-style",
            "personality_traits": ["competitive","direct","loyal","focused"],"values": ["guard with sword","prove growth"],"desires": ["guard in expedition","hone Light Blade"],"fears": ["impulse hurts books or allies"],"taboos": ["disrespect to Rudeus women"],"insecurities": ["distance from ideal"],"pride": "Mad Sword King and three styles","impulsiveness": "MEDIUM","patience": "MEDIUM","risk_tolerance": "HIGH","self_control": "MEDIUM","attachment_style": "bond via guard and spar","authority_attitude": "polite but blunt to Ariel","family_attitude": "belongs to Rudeus home","romantic_attitude": "hot for Rudeus","violence_attitude": "front sword","money_attitude": "none","status_attitude": "by strength","race_attitude": "no bias","religious_attitude": "none","loyalty": "HIGH","ambition": "HIGH","short_term_goals": ["labyrinth rear and swap","with Ghislaine"],"long_term_goals": ["handle Light Blade"],"obligations": ["guard Rudeus","respect Lilia"],"decision_tendencies": ["go first then listen","judge by blade"],"speech_tendencies": ["short challenge calling Rudeus"],"social_tendencies": ["careful with Lilia"],"conflict_tendencies": ["face enemy, controlled force"],"known_skills": ["Light Blade","North and Water basics"],"knowledge_state": ["dizzy transfer and labyrinth rules"],"relationship_tendencies": ["respect Ghislaine","rotate with Sylphy"],"behavior_changes_note": "from willful to controlled sword king","summary": "Mad Sword King guards and hones","visible_from_volume": 16,"visible_to_volume": None,"evidence_refs": ev(19,20)
        },
        {
            "profile_id": "CP16006","character_id": "E0045","phase_id": "P16006","phase_name": "Court guard","start_date": None,"end_date": None,"date_precision": "UNKNOWN","age_description": "young knight, Ariel side, Notos",
            "personality_traits": ["loyal","earnest","blunt","exploitable"],"values": ["Ariel kingship is mission","noble duty"],"desires": ["win via dragon king","reach Rudeus early"],"fears": ["sword fails lord","branded apostle"],"taboos": ["betray Ariel"],"insecurities": ["sword only decent, risks book"],"pride": "knightly courtesy and favor","impulsiveness": "MEDIUM","patience": "LOW","risk_tolerance": "MEDIUM","self_control": "MEDIUM","attachment_style": "values Ariel and Sylphy","authority_attitude": "inquires to both kings","family_attitude": "Notos duty","romantic_attitude": "retreats after learning Eris is wife","violence_attitude": "shield first","money_attitude": "trades network","status_attitude": "values lineage","race_attitude": "no bias","religious_attitude": "none","loyalty": "HIGH","ambition": "HIGH","short_term_goals": ["bring Rudeus together","guard Ariel in maze"],"long_term_goals": ["see coronation"],"obligations": ["guard Ariel","six-year network"],"decision_tendencies": ["act alone to contact Rudeus","plead bluntly"],"speech_tendencies": ["earnest plea to Rudeus","instant polite to Eris"],"social_tendencies": ["shuttles fort-Sharia"],"conflict_tendencies": ["block with body, plead with words"],"known_skills": ["court sword","network brokering"],"knowledge_state": ["knows human-god not self-aware","knows 13"],"relationship_tendencies": ["sought then watched by Rudeus","shares guard with Sylphy"],"behavior_changes_note": "from lone plea under suspicion to partial proof by blocking","summary": "Loyal hasty knight guards in suspicion gap","visible_from_volume": 16,"visible_to_volume": None,"evidence_refs": ev(10,11,23)
        },
        {
            "profile_id": "CP16007","character_id": "E0022","phase_id": "P16007","phase_name": "Sword king guard","start_date": None,"end_date": None,"date_precision": "UNKNOWN","age_description": "beast sword king, temp guard for Ariel",
            "personality_traits": ["taciturn","straight","dutiful","battle-loving"],"values": ["guard with sword","honor trust"],"desires": ["swat sparks by Ariel","fight strong"],"fears": ["fail lord"],"taboos": ["retreat"],"insecurities": ["poor speech"],"pride": "Black Wolf Sword King","impulsiveness": "LOW","patience": "HIGH","risk_tolerance": "MEDIUM","self_control": "HIGH","attachment_style": "loyal in deeds","authority_attitude": "obeys Ariel and Rudeus","family_attitude": "none","romantic_attitude": "none","violence_attitude": "front blade","money_attitude": "none","status_attitude": "by sword","race_attitude": "proud beast","religious_attitude": "none","loyalty": "HIGH","ambition": "LOW","short_term_goals": ["maze assist","vanguard"],"long_term_goals": ["escort to capital"],"obligations": ["temp guard trust"],"decision_tendencies": ["execute quietly"],"speech_tendencies": ["short affirmatives"],"social_tendencies": ["shoulder with Eris"],"conflict_tendencies": ["cut down head-on"],"known_skills": ["sword king sword"],"knowledge_state": ["knows Saurus many suspects"],"relationship_tendencies": ["cares for Eris as junior"],"behavior_changes_note": "takes post with few words, sharp blade","summary": "Taciturn loyal beast, expedition anchor","visible_from_volume": 16,"visible_to_volume": None,"evidence_refs": ev(19,)
        },
    ],
    "behavior_cases": [
        {"case_id": "BC16001","character_id": "E0001","phase_id": "P16001","phase_name": "Orsted subordinate early","volume_no": 16,"situation_type": "summon guardian","context": "Home, Orsted circle to fill absence","trigger": "Orsted gives binding circle","available_information": "knows needs great beast image","action": "second infusion to summon Leo and oath","verbal_response": "Leo protect family","emotional_response": "tense then relieved","goal_at_time": "fill leave gap","relationship_context": "Rudeus-Leo master-servant vs family as ward","social_context": "semi-public family rite","immediate_outcome": "Leo answers","long_term_outcome": "family deemed safe by Orsted","tags": ["TRUST","PROTECT","FAMILY"],"evidence_refs": ev(7,8)},
        {"case_id": "BC16002","character_id": "E0001","phase_id": "P16001","phase_name": "Orsted subordinate early","volume_no": 16,"situation_type": "vet suspect","context": "Door, Luke courting Eris","trigger": "see Luke down white-eyed","available_information": "notes diary and Orsted name Luke apostle","action": "carry in then ask human-god name and watch blank scratch","verbal_response": "heard human-god before?","emotional_response": "wary and ethical doubt","goal_at_time": "judge apostle","relationship_context": "watch vs guard Eris","social_context": "private home handling","immediate_outcome": "Luke denies says heard at Perugius too","long_term_outcome": "to report and watch","tags": ["SUSPICION","TRUST","NEGOTIATION"],"evidence_refs": ev(10,11)},
        {"case_id": "BC16003","character_id": "E0001","phase_id": "P16001","phase_name": "Orsted subordinate early","volume_no": 16,"situation_type": "report and receive orders","context": "Hut outside Sharia via ring compass","trigger": "need policy on Luke and curse","available_information": "human god controls three, curse blinds kin","action": "detail Leo and Luke accept three-man limit","verbal_response": "still persuade Perugius?","emotional_response": "resists killing and worries scale","goal_at_time": "calibrate help vs monitor","relationship_context": "subordinate vs watch target","social_context": "private hut avoids curse","immediate_outcome": "help confirmed","long_term_outcome": "dual track help plus intel control","tags": ["LOYALTY","AUTHORITY","NEGOTIATION"],"evidence_refs": ev(12,)},
        {"case_id": "BC16004","character_id": "E0001","phase_id": "P16001","phase_name": "Orsted subordinate early","volume_no": 16,"situation_type": "bridge camp","context": "Garden tea stalemate","trigger": "Ariel silent plea and Perugius cold","available_information": "knows Derrick would have bridged, king element asked","action": "relay limited Orsted intent propose Perugius pivot hear 13","verbal_response": "winning Perugius is key","emotional_response": "sympathy and caution","goal_at_time": "pull camp to dragon king pivot","relationship_context": "ally to Ariel wife-guard to Sylphy","social_context": "semi-public","immediate_outcome": "all listen to 13","long_term_outcome": "locks onto friends answer","tags": ["NEGOTIATION","TRUST","AUTHORITY"],"evidence_refs": ev(14,17)},
        {"case_id": "BC16005","character_id": "E0044","phase_id": "P16002","phase_name": "Fort waiting","volume_no": 16,"situation_type": "self reflect and ask help","context": "After generous thesis relay","trigger": "confronted why worry alone","available_information": "knows conceit limits, knows 13","action": "laugh bitterly stretch slap reset and tell 13 in detail","verbal_response": "tell me each detailed history","emotional_response": "shame to resolve","goal_at_time": "find king element via group history","relationship_context": "from test to trust with Rudeus","social_context": "private to meeting","immediate_outcome": "Luke adds side proof","long_term_outcome": "finds Cavani hint","tags": ["TRUST","FAILURE","SUCCESS"],"evidence_refs": ev(17,)},
        {"case_id": "BC16006","character_id": "E0001","phase_id": "P16001","phase_name": "Orsted subordinate early","volume_no": 16,"situation_type": "maze exploration","context": "Transfer to labyrinth 4km halls","trigger": "has Cavani direction and cover book","available_information": "knows no book destruction, familiars, age layers","action": "quiet march rest, trade with Bedobeto for bat diary and powerless child entry","verbal_response": "thing that will make Ariel happy","emotional_response": "relief that intel checks","goal_at_time": "answer dragon mock","relationship_context": "finder to Ariel tacit to Sylphy","social_context": "silent march","immediate_outcome": "got diary Ariel says knows answer","long_term_outcome": "audience ready","tags": ["DANGER","TRUST","SUCCESS"],"evidence_refs": ev(18,20,21,22)},
        {"case_id": "BC16007","character_id": "E0001","phase_id": "P16001","phase_name": "Orsted subordinate early","volume_no": 16,"situation_type": "combat cover","context": "Return books then slimes and snail on Ariel","trigger": "slow incomplete Ghislaine not done fourth slime through side","available_information": "Frost Nova only slows rock cannon crushes snail","action": "slow group then crush snail swap with Sylphy Eris Ghislaine Luke covers","verbal_response": "rock cannon","emotional_response": "instant decide then apologize","goal_at_time": "keep Ariel and all out","relationship_context": "swap with Sylphy side by side with Luke","social_context": "book-preserving fight","immediate_outcome": "snail crushed team safe","long_term_outcome": "Luke partly proven","tags": ["COMBAT","PROTECT","DANGER"],"evidence_refs": ev(23,)},
        {"case_id": "BC16008","character_id": "E0044","phase_id": "P16002","phase_name": "Fort waiting","volume_no": 16,"situation_type": "audience","context": "Hall twelve spirits","trigger": "king asks king element again","available_information": "holds friends answer","action": "answers friends around and inherits nameless will though feels off","verbal_response": "friends line","emotional_response": "fear then achievement","goal_at_time": "win dragon backing","relationship_context": "Q&A selection","social_context": "formal public","immediate_outcome": "endorsed and ordered transfer prep","long_term_outcome": "first prince parity","tags": ["AUTHORITY","SUCCESS","NEGOTIATION"],"evidence_refs": ev(24,)},
        {"case_id": "BC16009","character_id": "E0001","phase_id": "P16001","phase_name": "Orsted subordinate early","volume_no": 16,"situation_type": "postmortem and containment","context": "After endorsement transfer said dead","trigger": "order to activate shows no response","available_information": "only shortcut maybe sabotaged","action": "report third time accept Darius Luke verdict agree minimize to Ariel Sylphy Luke","verbal_response": "Ariel cannot be controlled","emotional_response": "heavy and guilty","goal_at_time": "seal intel seek land route","relationship_context": "hide to protect","social_context": "private report","immediate_outcome": "agree leak nothing hit apostles","long_term_outcome": "to covert help track","tags": ["SECRET","SUSPICION","LOYALTY"],"evidence_refs": ev(25,)},
        {"case_id": "BC16010","character_id": "E0001","phase_id": "P16001","phase_name": "Orsted subordinate early","volume_no": 16,"situation_type": "pre-expedition prep","context": "Sharia workshop and home","trigger": "clash with due date need armor and curse cure","available_information": "god armor curses bearer, Zanoba Cliff can forge","action": "use barrier tale get low-cost promise spar Light Blade 1-9","verbal_response": "Orsted barrier made me lose","emotional_response": "awe and moved to tears","goal_at_time": "raise survival and home care","relationship_context": "lie to protect friends, spar to respect wife","social_context": "drink with men and women together","immediate_outcome": "Cliff promises low-cost","long_term_outcome": "eight persons five horses one cart out","tags": ["FRIENDSHIP","FAMILY","TRAINING"],"evidence_refs": ev(26,)},
        {"case_id": "BC16011","character_id": "E0045","phase_id": "P16006","phase_name": "Court guard","volume_no": 16,"situation_type": "shield lord","context": "Maze slime through side","trigger": "Rudeus locks snail Ariel exposed","available_information": "knows control hard to avoid book hit","action": "turn and shield before Ariel block slime with body","verbal_response": "silent block","emotional_response": "tense to firm","goal_at_time": "prove as shield","relationship_context": "protect vs side-by-side","social_context": "team sync","immediate_outcome": "Ariel unhurt","long_term_outcome": "Rudeus rates not bad","tags": ["PROTECT","LOYALTY","COMBAT"],"evidence_refs": ev(23,)},
        {"case_id": "BC16012","character_id": "E0022","phase_id": "P16007","phase_name": "Sword king guard","volume_no": 16,"situation_type": "take guard duty","context": "Recommended to swat sparks by Ariel","trigger": "take sparks assignment","available_information": "Saurus death many suspects","action": "short call me Ghislaine then help vs slows and snail","verbal_response": "call me Ghislaine","emotional_response": "calm loyal","goal_at_time": "guard with sword king strength","relationship_context": "guard Ariel side Rudeus","social_context": "audience and maze guard","immediate_outcome": "rite done effective","long_term_outcome": "core vanguard","tags": ["LOYALTY","PROTECT","COMBAT"],"evidence_refs": ev(19,23)},
    ],
    "detailed_events": [
        {"event_id": "DE16001","event_type": "summon rite","title": "Summon Leo","timeline_event_id": "T0060","time_date": None,"time_precision": "UNKNOWN","time_note": "within month before court task, at home","volume_no": 16,"location_id": None,"participants": ["E0001","E0136"],"prerequisites": [{"prerequisite_id": "EP16001","prerequisite_type": "STATE","ref_id": None,"statement": "Orsted provides binding summon circle","evidence_refs": ev(6,)},{"prerequisite_id": "EP16002","prerequisite_type": "PERSON_PRESENT","ref_id": "E0001","statement": "Rudeus present with family to perform","evidence_refs": ev(6,)}],"dependencies": [],"state_changes": [{"change_id": "SC16001","change_kind": "pact","subject_id": "E0136","before": "unbound","after": "bound to guard family"},{"change_id": "SC16002","change_kind": "coverage","subject_id": "E0001","before": "gap","after": "gap filled by beast"}],"trigger": "fill absence from serving Orsted","actions": ["witness circle start","infuse with great beast image","oath guard family"],"outcome": "Leo bonds, Orsted deems home safe","relationship_change_ids": ["RC16001"],"belief_ids": ["BL16001"],"canon_importance": "MAJOR","evidence_refs": ev(7,8,9)},
        {"event_id": "DE16002","event_type": "explore","title": "Labyrinth and diary find","timeline_event_id": "T0061","time_date": None,"time_precision": "UNKNOWN","time_note": "during Ariel cooperation, transferred to maze","volume_no": 16,"location_id": None,"participants": ["E0001","E0044","E0006","E0045","E0021","E0022","E0137"],"prerequisites": [{"prerequisite_id": "EP16003","prerequisite_type": "KNOWLEDGE","ref_id": None,"statement": "Cavani is dragon king pivot","evidence_refs": ev(18,)},{"prerequisite_id": "EP16004","prerequisite_type": "PERSON_ALIVE","ref_id": "E0137","statement": "Bedobeto demon king trades book for book","evidence_refs": ev(21,)}],"dependencies": [{"dependency_id": "ED16001","dependency_type": "REQUIRES","target_event_id": "T0060","statement": "home secured by beast allows leave"},{"dependency_id": "ED16002","dependency_type": "ENABLES","target_event_id": "DE16003","statement": "diary enables audience win"}],"state_changes": [{"change_id": "SC16003","change_kind": "intel","subject_id": "E0044","before": "no answer","after": "has friends history and diary"},{"change_id": "SC16004","change_kind": "recognition","subject_id": "E0001","before": "unknown crest","after": "recognizes Derrick crest"}],"trigger": "need proof to persuade dragon king","actions": ["transfer silent march","trade with Bedobeto","find bat diary and powerless child entry and return"],"outcome": "Ariel says knows answer, audience ready","relationship_change_ids": ["RC16002"],"belief_ids": ["BL16002","BL16003"],"canon_importance": "MAJOR","evidence_refs": ev(18,21,22)},
        {"event_id": "DE16003","event_type": "audience verdict","title": "Perugius audience and endorsement","timeline_event_id": "T0062","time_date": None,"time_precision": "UNKNOWN","time_note": "right after maze via Sylvaril","volume_no": 16,"location_id": None,"participants": ["E0044","E0029","E0001","E0006","E0045"],"prerequisites": [{"prerequisite_id": "EP16005","prerequisite_type": "KNOWLEDGE","ref_id": None,"statement": "Ariel holds diary and friends history","evidence_refs": ev(22,)},{"prerequisite_id": "EP16006","prerequisite_type": "PERSON_ALIVE","ref_id": "E0029","statement": "Perugius available at fort","evidence_refs": ev(24,)}],"dependencies": [{"dependency_id": "ED16003","dependency_type": "REQUIRES","target_event_id": "DE16002","statement": "need artifact"}],"state_changes": [{"change_id": "SC16005","change_kind": "camp","subject_id": "E0044","before": "no dragon backing","after": "has backing parity"},{"change_id": "SC16006","change_kind": "order","subject_id": "E0029","before": "cold","after": "orders transfer prep"}],"trigger": "king asks king element again","actions": ["Ariel states friends around","king endorses orders transfer prep"],"outcome": "decisive backing secured","relationship_change_ids": ["RC16003"],"belief_ids": ["BL16004"],"canon_importance": "MAJOR","evidence_refs": ev(24,)},
        {"event_id": "DE16004","event_type": "setback","title": "Transfer circles dead","timeline_event_id": "T0063","time_date": None,"time_precision": "UNKNOWN","time_note": "right after audience test","volume_no": 16,"location_id": None,"participants": ["E0044","E0001","E0006","E0045"],"prerequisites": [{"prerequisite_id": "EP16007","prerequisite_type": "STATE","ref_id": None,"statement": "fort has direct circles to Asura","evidence_refs": ev(24,)}],"dependencies": [{"dependency_id": "ED16004","dependency_type": "CAUSES","target_event_id": "DE16003","statement": "order exposes dead circles"}],"state_changes": [{"change_id": "SC16007","change_kind": "passage","subject_id": "E0044","before": "can transfer at once","after": "all broken need land"}],"trigger": "Sylvaril ordered to activate","actions": ["go check","report all broken silent"],"outcome": "return blocked need new path","relationship_change_ids": [],"belief_ids": ["BL16005"],"canon_importance": "MAJOR","evidence_refs": ev(24,)},
        {"event_id": "DE16005","event_type": "prep","title": "Pre-expedition armor and home","timeline_event_id": None,"time_date": None,"time_precision": "UNKNOWN","time_note": "days before leaving Sharia","volume_no": 16,"location_id": None,"participants": ["E0001","E0021","E0022","E0006"],"prerequisites": [{"prerequisite_id": "EP16008","prerequisite_type": "PERSON_PRESENT","ref_id": "E0001","statement": "Zanoba and Cliff at workshop","evidence_refs": ev(26,)}],"dependencies": [{"dependency_id": "ED16005","dependency_type": "ENABLES","target_event_id": "T0063","statement": "armor and curse plan enables land march"}],"state_changes": [{"change_id": "SC16008","change_kind": "gear","subject_id": "E0001","before": "high cost not cured","after": "low-cost commissioned plus Julie ver"},{"change_id": "SC16009","change_kind": "care","subject_id": "E0006","before": "torn guard vs mother","after": "plan with Lilia Aisha for Lucy"}],"trigger": "land to Asura may clash with birth","actions": ["get low-cost promise with barrier tale","spar Light Blade 1-9","women meet care plan"],"outcome": "eight persons five horses one cart depart","relationship_change_ids": ["RC16004"],"belief_ids": ["BL16006"],"canon_importance": "MINOR","evidence_refs": ev(26,)},
    ],
    "items": [
        {"item_id": "IT16001","canonical_name": "Derrick diary","aliases": ["butterfly diary","bat crest diary"],"category": "book","subcategory": "diary","description": "Derrick record on Ariel and Luke and kingship view, bat crest cover becomes persuasion proof","material": "paper","size": "single","weight": None,"durability": None,"rarity": "unique","value_information": "priceless as proof for succession","currency": None,"creator": "E0046","origin": "labyrinth collection","manufacturer": None,"abilities": [],"effects": ["prove friends king element"],"requirements": [],"limitations": [],"first_appearance_volume": 16,"first_appearance_line": 146512,"visible_from_volume": 16,"evidence_refs": ev(22,)}
    ],
    "item_instances": [],
    "abilities": [
        {"ability_id": "AB16001","name": "guardian summon","aliases": ["holy beast summon"],"ability_type": "MAGIC","school": "summoning","element": None,"tier": "high","requirements": ["binding circle from Orsted"],"preconditions": ["image great beast infusion"],"mana_cost_if_known": "full magic infusion","stamina_cost_if_known": None,"range_if_known": "within circle","duration_if_known": "lasting pact","effects": ["summon holy Leo","bind guard vow"],"limitations": ["needs matching circle and image"],"counters": [],"qualitative_power": "enough for Orsted to deem family safe","learning_method": ["Orsted gives circle","image infusion"],"known_users": ["E0001"],"evidence_refs": ev(7,8)}
    ],
    "power_comparisons": [],
    "world_rules": [
        {"rule_id": "WR16001","domain": "MAGIC","statement": "labyrinth transfer circles are direct shortcut to Asura and can all be sabotaged dead","scope": "Sharia-Asura transfer net","exceptions": "no shortcut then land","confidence": "EXPLICIT","visible_from_volume": 16,"evidence_refs": ev(24,)},
        {"rule_id": "WR16002","domain": "SOCIETY","statement": "king element in dragon trial is many friends around and inheriting nameless will","scope": "Perugius selection Q&A","exceptions": "feels off still pickable for caliber","confidence": "EXPLICIT","visible_from_volume": 16,"evidence_refs": ev(22,24)},
        {"rule_id": "WR16003","domain": "MAGIC","statement": "powerless child ability nulls other blessed children seen as kill-on-sight extreme danger","scope": "blessed child system","exceptions": "already dead only records","confidence": "EXPLICIT","visible_from_volume": 16,"evidence_refs": ev(21,)}
    ],
    "locations": [],"routes": [],"travel_observations": [],"organizations": [],"political_states": [],"species": [],"creatures": [],
    "beliefs": [
        {"belief_id": "BL16001","owner_id": "E0001","topic": "beast guard","statement": "Leo suffices to guard home leaving safe","certainty": "EXPLICIT","belief_state": "FACT_KNOWN","learned_from": None,"learned_at_volume": 16,"learned_method": "lived summon and Orsted verdict","is_true_in_world": True,"visible_from_volume": 16,"visible_to_volume": None,"note": "Orsted says safe and oath set","evidence_refs": ev(8,9)},
        {"belief_id": "BL16002","owner_id": "E0001","topic": "Cavani element","statement": "Cavani win is friends around and nameless will","certainty": "EXPLICIT","belief_state": "FACT_KNOWN","learned_from": "E0001","learned_at_volume": 16,"learned_method": "labyrinth records and Bedobeto book","is_true_in_world": True,"visible_from_volume": 16,"visible_to_volume": None,"note": "seven heroes plus adventurers","evidence_refs": ev(21,22)},
        {"belief_id": "BL16003","owner_id": "E0044","topic": "king answer","statement": "friends around is king element ready for dragon","certainty": "EXPLICIT","belief_state": "FACT_KNOWN","learned_from": "E0001","learned_at_volume": 16,"learned_method": "read diary handed by Rudeus","is_true_in_world": True,"visible_from_volume": 16,"visible_to_volume": None,"note": "said knows answer then answered","evidence_refs": ev(22,)},
        {"belief_id": "BL16004","owner_id": "E0001","topic": "apostles","statement": "Darius and Luke are current apostles","certainty": "EXPLICIT","belief_state": "INFERRED","learned_from": "E0079","learned_at_volume": 16,"learned_method": "Orsted timing verdict","is_true_in_world": True,"visible_from_volume": 16,"visible_to_volume": None,"note": "hut names two","evidence_refs": ev(25,)},
        {"belief_id": "BL16005","owner_id": "E0001","topic": "circles dead","statement": "Asura circles all destroyed","certainty": "EXPLICIT","belief_state": "FACT_KNOWN","learned_from": "E0079","learned_at_volume": 16,"learned_method": "Sylvaril direct report","is_true_in_world": True,"visible_from_volume": 16,"visible_to_volume": None,"note": "order then silence","evidence_refs": ev(24,)},
        {"belief_id": "BL16006","owner_id": "E0001","topic": "curse handling","statement": "curse skews view of Orsted, Ariel more resistant","certainty": "EXPLICIT","belief_state": "INFERRED","learned_from": None,"learned_at_volume": 16,"learned_method": "contrast of Sylphy Roxy disbelief vs Ariel lenience","is_true_in_world": True,"visible_from_volume": 16,"visible_to_volume": None,"note": "Ariel calls Orsted generous","evidence_refs": ev(15,)}
    ],
    "economic_observations": [],
    "relationship_changes": [
        {"change_id": "RC16001","source_id": "E0001","target_id": "E0136","dimension": "pact","before": "none","trigger": "second infusion summon beast","after": "bound master-servant","at_volume": 16,"at_date": None,"evidence_refs": ev(7,8)},
        {"change_id": "RC16002","source_id": "E0001","target_id": "E0044","dimension": "ally","before": "cooperation thin no proof","trigger": "hand diary and co-prove friends","after": "ready audience partners","at_volume": 16,"at_date": None,"evidence_refs": ev(22,)},
        {"change_id": "RC16003","source_id": "E0044","target_id": "E0029","dimension": "affiliation","before": "cold many asks no result","trigger": "answer friends around audience","after": "endorsed as aide","at_volume": 16,"at_date": None,"evidence_refs": ev(24,)},
        {"change_id": "RC16004","source_id": "E0001","target_id": "E0006","dimension": "sync","before": "separate roles with gaps","trigger": "maze swap and night talk divide","after": "silent sync and care pact","at_volume": 16,"at_date": None,"evidence_refs": ev(23,)}
    ],
    "speech_profiles": [
        {"profile_id": "ST16001","character_id": "E0001","phase_id": "P16001","phase_name": "Orsted subordinate early","politeness": "report register to lord, cooperative to Ariel, frank to family","sentence_length": "mid-long, list 10 nodes when reporting","address_habits": "calls Orsted lord Ariel lady Sylphy","emotion_expression": "externalize tension as scary and sly smile","anger_expression": "restrained sigh over scold","shy_expression": "shy aside on flirt and fondness","intimate_speech": "home night talk to wives","stranger_speech": "vet then ask human-god to strangers","superior_speech": "deferential probes do you know answer","inferior_speech": "imperative oath to Leo","canonical_examples": ["protect these family before you","have you heard human-god"],"visible_from_volume": 16,"evidence_refs": ev(3,6,8)},
        {"profile_id": "ST16002","character_id": "E0044","phase_id": "P16002","phase_name": "Fort waiting","politeness": "ultra formal at audience, self-mocking private","sentence_length": "long unhurried public, faint short private","address_habits": "calls Rudeus mister Perugius lord","emotion_expression": "shift mood via tea and stretch","anger_expression": "not shout but Q&A","shy_expression": "joke about erotic novel to hide fear","intimate_speech": "frank about friends","stranger_speech": "formal welcome to spirits and Rudeus","superior_speech": "solemn direct to dragon","inferior_speech": "gentle encourage to retainers","canonical_examples": ["I know the answer","many friends around"],"visible_from_volume": 16,"evidence_refs": ev(16,22,24)}
    ],
    "character_quirks": [
        {"quirk_id": "QK16001","character_id": "E0001","phase_id": "P16001","category": "verbal tic","name": "inner roast narration","description": "externalize tension as scary sly smile metaphors to self-mock and relieve","intensity": "MEDIUM","frequency": "often","triggers": ["facing Orsted stern face","before bad news"],"preferred_targets": ["E0079"],"avoided_targets": [],"public_expression": None,"private_expression": None,"behavior_patterns": ["exaggerate then cut to point"],"verbal_patterns": ["seems to be shot"],"boundaries": ["not before Ariel group"],"exceptions": ["private monologue or half joke to Sylphy"],"start_date": None,"end_date": None,"visible_from_volume": 16,"visible_to_volume": None,"evidence_type": "CANON_EXPLICIT","confidence": "EXPLICIT","evidence_refs": ev(1,6)},
        {"quirk_id": "QK16002","character_id": "E0044","phase_id": "P16002","category": "ritual","name": "tea stretch reset","description": "after not-fit-for-king self blame sweep hair high stretch twist neck slap to force switch","intensity": "MEDIUM","frequency": "occasional","triggers": ["called lone worry into self pity"],"preferred_targets": [],"avoided_targets": [],"public_expression": None,"private_expression": None,"behavior_patterns": ["self mock then body switch back to focus"],"verbal_patterns": ["my conceit limited me"],"boundaries": ["only inner circle"],"exceptions": [],"start_date": None,"end_date": None,"visible_from_volume": 16,"visible_to_volume": None,"evidence_type": "CANON_EXPLICIT","confidence": "EXPLICIT","evidence_refs": ev(16,17)}
    ],
    "character_preferences": [
        {"preference_id": "PF16001","character_id": "E0001","phase_id": "P16001","preference_type": "like","target": "book proof","description": "prefer history pictures diary proof over empty persuasion to dragon or kin","intensity": "HIGH","context": "king persuasion and dragon Q&A","visible_from_volume": 16,"visible_to_volume": None,"evidence_type": "CANON_EXPLICIT","confidence": "EXPLICIT","evidence_refs": ev(18,22)},
        {"preference_id": "PF16002","character_id": "E0044","phase_id": "P16002","preference_type": "like","target": "king of friends","description": "endorse king inheriting nameless will with friends not lone","intensity": "HIGH","context": "after co-proving Cavani element with Rudeus","visible_from_volume": 16,"visible_to_volume": None,"evidence_type": "CANON_EXPLICIT","confidence": "EXPLICIT","evidence_refs": ev(22,)}
    ],
    "body_language_profiles": [
        {"profile_id": "BY16001","character_id": "E0044","phase_id": "P16002","phase_name": "Fort waiting","happy_signs": ["smile after audience","nod with Luke"],"angry_signs": [],"nervous_signs": ["black circles faint speech at tea"],"embarrassed_signs": [],"lying_signs": [],"fear_signs": [],"thinking_signs": ["silent gaze to clouds before resolve"],"affection_signs": ["bow return to Sylphy Luke"],"hostility_signs": [],"visible_from_volume": 16,"visible_to_volume": None,"evidence_refs": ev(14,16,24)}
    ],
    "character_personas": [
        {"persona_id": "PN16001","character_id": "E0001","phase_id": "P16001","persona_type": "emissary","description": "loyal emissary to Orsted: public cooperator to Ariel private intel line, least-privilege sharing","speech_style": "switch register and secret tongue by audience","behavior_traits": ["report","hand book","ask human-god name","hide to protect"],"visible_from_volume": 16,"visible_to_volume": None,"evidence_refs": ev(3,25)}
    ],
    "canon_conflicts": [],
    "canon_gaps": [
        {"gap_id": "GAP16001","domain": "magic","question": "whether a living powerless child remains to cure Zenith curse","why_needed": "Rudeus seeks cure affects post-expedition medical route","searched_volumes": [16],"status": "OPEN","possible_sources": "deeper maze or dragon archives","note": "only dead rumor in this volume"}
    ]
}

# Validate via model
try:
    b = EnrichmentBatch.from_json(batch)
    print("from_json ok", b.counts())
except Exception as e:
    print("from_json fail", e)
    raise

out = pathlib.Path("data/canon_enriched/V016.json")
out.write_text(json.dumps(batch, ensure_ascii=False, indent=2), encoding="utf-8")
print("wrote", out)

reg = load_entity_registry(pathlib.Path("data/canon"))
batches = load_enrichment_batches(pathlib.Path("data/canon_enriched"))
report = verify_enrichment(batches, doc, reg)
print("clean", report.is_clean, "errors", len(report.errors))
for e in report.errors:
    print(e.code, e.path, e.message)
pathlib.Path("data/canon_enriched/report.json").write_text(json.dumps(report.to_json(), ensure_ascii=False, indent=2), encoding="utf-8")
