import json, pathlib
from overlord_worldsim.canon.parse import parse_source
from overlord_worldsim.canon.enrich_model import (
    EvidenceRef, EvidenceType, EnrichmentBatch, CharacterProfile, BehaviorCase, DetailedEvent,
    EventPrerequisite, EventPrerequisiteKind, EventDependency, EventDependencyKind, StateChange,
    Belief, BeliefState, RelationshipChange, SpeechProfile, CharacterQuirk, CharacterPreference,
    BodyLanguageProfile, CharacterPersona, ItemDef, AbilityProfile, WorldRule, WorldRuleDomain,
    AbilityType, CanonGap, GapStatus, EventImportance
)
from overlord_worldsim.canon.extract_model import Confidence, DatePrecision
from overlord_worldsim.canon.enrich_registry import load_enrichment_batches, load_entity_registry
from overlord_worldsim.canon.enrich_verifier import verify_enrichment

raw = pathlib.Path("data/raw/无职转生TXT合集.txt").read_text(encoding="utf-8")
doc = parse_source(raw)
v16_chunks = [c for c in doc.chunks if c.volume_no==16]
# pick 26 indices spread across volume
picked_indices = [0,1,2,5,6,8,10,12,13,15,18,22,25,30,35,40,45,50,55,60,65,70,80,85,90,95]
picked = [v16_chunks[i] for i in picked_indices if i < len(v16_chunks)]

notes = [
    "卷首回顾：鲁迪成为奥尔斯帝德部下、与艾莉丝再婚，开篇定调本卷主线为首次任务",
    "奥尔斯帝德审阅未来日记，追问人神对话十次节点，要求鲁迪吐露全程",
    "秘宝与龙将传承：五龙将持有、卡奥斯份已回收，拉普拉斯八十年后复活方集齐",
    "朵莉丝缇娜与大流士上级大臣的诱拐指控，可作倒阁名目",
    "过渡期任务：一个月内将佩尔基乌斯拉拢至爱丽儿阵营，为王位铺决定性后盾",
    "鲁迪在家人面前启动奥尔斯帝德所给召唤魔法阵，家人半信半疑、洛琪希取杖戒备",
    "首次召唤误召阿尔曼菲，二度以最伟大动物为意象灌魔，七彩光中召出圣兽",
    "雷欧认主：舔手嗅味后扑向洛琪希，鲁迪下达守护家人使命获汪声应答",
    "雷欧安顿两日：项圈狗屋、玄关站岗、巡宅安抚露西、护送诺伦等自宅警备表现",
    "路克突访撩艾莉丝被击倒，鲁迪判定其为最可疑人神使徒候补",
    "路克陈情：六年经营人脉仍缺决定性要素，佩尔基乌斯发言力与战力不可缺",
    "人神可同时操控三人，奥尔斯帝德以曾战剑神北神魔王为例佐证上限",
    "鲁迪向希露菲解释：让爱丽儿成王为百年布局，需借阿斯拉权力解非腕力问题",
    "空要庭园茶会：爱丽儿等呈关机疲惫态，七星尴尬回避",
    "奥尔斯帝德在空要与七星喝茶、希尔瓦莉尔泼茶亦不动怒，爱丽儿评其宽大",
    "爱丽儿自述持有不符之力者毁灭台词，坦言自认不适合为王的动摇",
    "佩尔基乌斯宅心仁厚论：独烦乃自以为是致受限，伸懒腰拍脸切换",
    "鲁迪与奥尔斯帝德密报卡瓦尼斯情报，获赠书封备用答案",
    "绍罗斯死因系削弱伯雷亚斯削弱第一王子派的谋略多嫌未破",
    "图书迷宫转移眩晕类人神梦境，初体验者皆面露疑惑",
    "书库外环约三百年后书籍无卡瓦尼斯，走四公里未绕一圈转内环渐近中心",
    "迪利克蝶纹日记现形：蝙蝠纹章，爱丽儿震惊认出为关键史料",
    "迷宫混战：迟缓史莱姆与树绳蜗牛并发，岩炮弹粉碎蜗牛、路克补位护爱丽儿",
    "晋见之间十二精灵环立，佩尔基乌斯虽觉答案不中意仍宣告相助并备转移阵",
    "小屋第三次会面：使徒锁定大流士与路克，爱丽儿被判不可操控",
    "远征前夜男子会：以结界说辞请克里夫扎诺巴低耗化重制魔导铠",
]

evidence = []
for idx, chunk in enumerate(picked):
    eid = f"EV160{idx+1:02d}"
    note = notes[idx] if idx < len(notes) else f"V16证据{idx+1}"
    evidence.append(EvidenceRef(
        evidence_id=eid, volume_no=16, unit_id=chunk.unit_id, chapter_title=chunk.chapter_title,
        source_start_line=chunk.source_start_line, source_end_line=chunk.source_end_line,
        evidence_type=EvidenceType.CANON_EXPLICIT, confidence=Confidence.EXPLICIT, note=note,
    ))

def ev(*nums):
    return tuple(f"EV160{n:02d}" for n in nums)

profiles = [
    CharacterProfile(profile_id="CP16001", character_id="E0001", phase_id="P16001", phase_name="奥尔斯帝德部下初期", start_date=None, end_date=None, date_precision=DatePrecision.UNKNOWN, age_description="约18岁，夏利亚已婚家主，初任龙神部下", personality_traits=("谨慎","重家庭","责任感强","好学"), values=("守护家人","履行对龙神承诺","诚实生活"), desires=("确保家人安全","助爱丽儿成王以抗人神"), fears=("人神再操控亲近者","诅咒致亲友误判"), taboos=("对家人过度隐瞒",), insecurities=("失言致奥尔斯帝德不信",), pride="无咏唱与庞大魔力", impulsiveness="LOW", patience="HIGH", risk_tolerance="MEDIUM", self_control="HIGH", attachment_style="对三妻与妹妹高度依恋", authority_attitude="对奥尔斯帝德敬畏服从，对佩尔基乌斯礼敬", family_attitude="以圣兽延伸家庭守护", romantic_attitude="已娶三妻，珍视羁绊", violence_attitude="非必要不杀，必要时以岩炮弹应对", money_attitude="远征开支由夏利亚支撑", status_attitude="不求爵位只求盟友", race_attitude="视圣兽与精灵为同伴", religious_attitude="无", loyalty="HIGH", ambition="MODERATE", short_term_goals=("召唤守护兽","说服佩尔基乌斯","取得迪利克日记"), long_term_goals=("百年后助奥尔斯帝德胜人神",), obligations=("奥尔斯帝德首次任务","家庭守护契约"), decision_tendencies=("先密报再与希露菲商量","以书籍实证说服"), speech_tendencies=("对龙王敬语报告体","对家人坦诚与隐瞒并存"), social_tendencies=("在空要谨慎递话",), conflict_tendencies=("以外交与证据化解龙王疑虑",), known_skills=("无咏唱多系魔法","召唤魔法","岩炮弹"), knowledge_state=("知十次人神接触","知秘宝与五龙将","知迪利克与卡瓦尼斯关联"), relationship_tendencies=("对路克保持审视","对爱丽儿协力不过度卖弄名号"), behavior_changes_note="从独力作战转向建构情报与同盟网络", summary="初为龙神属下的鲁迪，以圣兽守家、以史料说服龙王。", visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(6,7,8,12,22)),
    CharacterProfile(profile_id="CP16002", character_id="E0044", phase_id="P16002", phase_name="空要待机期", start_date=None, end_date=None, date_precision=DatePrecision.UNKNOWN, age_description="约十六七岁，阿斯拉第二公主，流亡夏利亚", personality_traits=("坚韧","聪慧","能屈能伸","善演"), values=("以优雅维系统治形象","才华即人脉"), desires=("取得佩尔基乌斯后盾以成女王","告慰十三旧部"), fears=("被判不适合为王","再失重要之人"), taboos=("在部下面前久露软弱",), insecurities=("对自我王适合性动摇",), pride="王族礼法与看人眼光", impulsiveness="MEDIUM", patience="MEDIUM", risk_tolerance="MEDIUM", self_control="HIGH", attachment_style="对希露菲路克高度信任", authority_attitude="对佩尔基乌斯敬而谈判", family_attitude="与王家兄弟对立", romantic_attitude="与路克为君臣", violence_attitude="委于护卫", money_attitude="以礼遇换支持", status_attitude="视王权为责任", race_attitude="接纳精灵与兽族", religious_attitude="无", loyalty="HIGH", ambition="HIGH", short_term_goals=("答出成王要素","修复与龙王关系","取得转移通道"), long_term_goals=("登上阿斯拉王位",), obligations=("对十三旧部的追思",), decision_tendencies=("先听完整经历再抉择","以茶会缓和紧绷"), speech_tendencies=("公开端庄敬语","私下坦露自嘲"), social_tendencies=("以庭园茶会维系人际",), conflict_tendencies=("以问答与礼仪应对龙王考验",), known_skills=("政略洞察","人才网罗"), knowledge_state=("知朵莉丝缇娜倒阁价值","知卡瓦尼斯身边挚友要素"), relationship_tendencies=("对鲁迪由试探转托付","对路克希露菲互为支柱"), behavior_changes_note="从焦虑关机到以史料重拾王的自觉", summary="在走投无路中重拾王者的爱丽儿，以挚友答案赢得龙王支持。", visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(14,15,16,17,22,24)),
    CharacterProfile(profile_id="CP16003", character_id="E0006", phase_id="P16003", phase_name="护卫兼妻子期", start_date=None, end_date=None, date_precision=DatePrecision.UNKNOWN, age_description="少年后半，护卫兼鲁迪第一妻子，育露西", personality_traits=("温柔","坚定","重友情","敏锐"), values=("朋友与家人并重","诚实与守护"), desires=("助爱丽儿成王不危及孩子","被鲁迪信赖"), fears=("被卷入叛徒指控","路克冒险致伤"), taboos=("对友人见死不救",), insecurities=("在两阵营间拉扯",), pride="精准配合与瞬时理解", impulsiveness="LOW", patience="HIGH", risk_tolerance="MEDIUM", self_control="HIGH", attachment_style="对鲁迪与爱丽儿双重忠诚", authority_attitude="对爱丽儿与龙神皆敬重", family_attitude="以露西为重", romantic_attitude="对鲁迪深爱", violence_attitude="以风魔法掩护见长", money_attitude="无突出", status_attitude="不以王族高低论人", race_attitude="接纳各族", religious_attitude="无", loyalty="HIGH", ambition="MODERATE", short_term_goals=("迷宫中前后卫切换","说服艾莉丝轮值"), long_term_goals=("兼顾母亲与护卫",), obligations=("护卫誓言","母亲责任"), decision_tendencies=("以眼神即时配合","先安抚再讲理"), speech_tendencies=("对鲁迪短句呼应","对爱丽儿恭敬护卫语"), social_tendencies=("女子会中坦诚",), conflict_tendencies=("以掩护补位取胜",), known_skills=("风系辅助","无言配合"), knowledge_state=("知诅咒致偏差","知转移禁忌"), relationship_tendencies=("与艾莉丝轮值互助","与路克互补"), behavior_changes_note="从担心被隐瞒到主动承担转运与护卫", summary="在友与家间权衡的希露菲，以默契支撑远征。", visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(13,17,23)),
    CharacterProfile(profile_id="CP16004", character_id="E0029", phase_id="P16004", phase_name="空要龙王期", start_date=None, end_date=None, date_precision=DatePrecision.UNKNOWN, age_description="龙族王，空要城主，十二精灵之主", personality_traits=("高傲","重义","考验成性","宅心仁厚"), values=("挚友与信义","王应继无名者遗志"), desires=("择可信之王托付","延续打倒拉普拉斯遗志"), fears=("托付非人",), taboos=("轻慢试炼问答",), insecurities=("对龙神亦不轻易妥协",), pride="甲龙王之名与发言力", impulsiveness="LOW", patience="MEDIUM", risk_tolerance="LOW", self_control="HIGH", attachment_style="以试炼择主", authority_attitude="自身即权威", family_attitude="以精灵为眷属", romantic_attitude="无", violence_attitude="以威仪掌控", money_attitude="无", status_attitude="视器量不视出身", race_attitude="统御精灵", religious_attitude="无", loyalty="HIGH", ambition="LOW", short_term_goals=("考验成王要素","备转移排场"), long_term_goals=("择明君稳阿斯拉",), obligations=("对七英雄精神承续",), decision_tendencies=("以器量判断"), speech_tendencies=("宣告式威严古风",), social_tendencies=("晋见之间居中裁决",), conflict_tendencies=("以问答定去留",), known_skills=("转移魔法阵","要塞统治"), knowledge_state=("知人神名并警惕","知卡瓦尼斯挚友史"), relationship_tendencies=("对爱丽儿从听而不决到幕僚","对鲁迪视为外援考验"), behavior_changes_note="从屡问不答到主动助阵", summary="以试炼择主的甲龙王，转为爱丽儿最强后盾。", visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(18,22,24)),
    CharacterProfile(profile_id="CP16005", character_id="E0021", phase_id="P16005", phase_name="护卫同行期", start_date=None, end_date=None, date_precision=DatePrecision.UNKNOWN, age_description="狂剑王，鲁迪第三妻子，已学多流", personality_traits=("好胜","直率","重情","专注"), values=("以剑守护同伴","以行动证成长"), desires=("远征中护住同伴","精进光之太刀"), fears=("冲动伤及书籍或同伴",), taboos=("对鲁迪家女性不敬",), insecurities=("距离感自省",), pride="狂剑王与三流派所学", impulsiveness="MEDIUM", patience="MEDIUM", risk_tolerance="HIGH", self_control="MEDIUM", attachment_style="以护卫与比试维系", authority_attitude="对爱丽儿礼敬保留直言", family_attitude="视鲁迪家为归属", romantic_attitude="对鲁迪热烈", violence_attitude="以前卫剑技为长", money_attitude="无", status_attitude="以实力论人", race_attitude="无偏见", religious_attitude="无", loyalty="HIGH", ambition="HIGH", short_term_goals=("迷宫殿后与切换","与基列奴配合"), long_term_goals=("能应付光之太刀",), obligations=("鲁迪护卫","尊重莉莉雅"), decision_tendencies=("先行再听令","以剑直观敌强弱"), speech_tendencies=("短句挑战式直呼鲁迪",), social_tendencies=("与莉莉雅谨慎对话",), conflict_tendencies=("正面迎敌受控力道",), known_skills=("光之太刀","北帝与水神基础"), knowledge_state=("知转移眩晕与迷宫规矩",), relationship_tendencies=("对基列奴尊敬","对希露菲轮值互助"), behavior_changes_note="从任性到能轮值与控力道的成熟剑王", summary="随行远征的狂剑王，以剑为盾护队并精进。", visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(19,20)),
    CharacterProfile(profile_id="CP16006", character_id="E0045", phase_id="P16006", phase_name="宫廷护卫期", start_date=None, end_date=None, date_precision=DatePrecision.UNKNOWN, age_description="青年骑士，爱丽儿侧近，诺托斯出身", personality_traits=("忠诚","认真","直言","易被利用"), values=("爱丽儿成王为使命","贵族责任"), desires=("以龙王之力成王","尽早联络鲁迪"), fears=("剑术不足致主受害","被误判为使徒"), taboos=("背离爱丽儿",), insecurities=("剑术仅独当一面难控毁书",), pride="护卫礼仪与知遇", impulsiveness="MEDIUM", patience="LOW", risk_tolerance="MEDIUM", self_control="MEDIUM", attachment_style="对爱丽儿与希露菲重义", authority_attitude="对龙王与龙神探询", family_attitude="诺托斯家责任", romantic_attitude="知艾莉丝为鲁迪妻后礼退", violence_attitude="持剑护卫为先", money_attitude="以人脉换支持", status_attitude="重王统", race_attitude="无偏见", religious_attitude="无", loyalty="HIGH", ambition="HIGH", short_term_goals=("促成与鲁迪合流","迷宫护爱丽儿"), long_term_goals=("见证登基",), obligations=("护卫爱丽儿","六年人脉承诺"), decision_tendencies=("独断联络鲁迪","直言陈情"), speech_tendencies=("对鲁迪认真陈情体","对艾莉丝瞬切礼敬"), social_tendencies=("往返空要夏利亚",), conflict_tendencies=("以身挡敌","以言直谏"), known_skills=("宫廷剑术","人脉斡旋"), knowledge_state=("知人神名不自认受控","知十三旧部"), relationship_tendencies=("对鲁迪由求援到被审视","对希露菲共担护卫"), behavior_changes_note="从独断求援被疑到以挡敌部分自证", summary="忠诚急切的宫廷骑士，在怀疑与信任夹缝中护主。", visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(10,11,23)),
    CharacterProfile(profile_id="CP16007", character_id="E0022", phase_id="P16007", phase_name="剑王护卫期", start_date=None, end_date=None, date_precision=DatePrecision.UNKNOWN, age_description="兽族女剑王，爱丽儿临时护卫", personality_traits=("寡言","忠直","重义","好战"), values=("以剑护主","不负所托"), desires=("拍掉爱丽儿身边火花","与强敌一战"), fears=("失职致主受害",), taboos=("临阵退缩",), insecurities=("言语不擅",), pride="黑狼剑王之名", impulsiveness="LOW", patience="HIGH", risk_tolerance="MEDIUM", self_control="HIGH", attachment_style="以行动表忠", authority_attitude="对爱丽儿与鲁迪皆服从", family_attitude="无", romantic_attitude="无", violence_attitude="以剑前卫", money_attitude="无", status_attitude="以剑论人", race_attitude="兽族自豪", religious_attitude="无", loyalty="HIGH", ambition="LOW", short_term_goals=("迷宫协防","远征前卫"), long_term_goals=("护爱丽儿至王都",), obligations=("临时护卫之托",), decision_tendencies=("寡言执行"), speech_tendencies=("短促肯定句",), social_tendencies=("与艾莉丝并肩",), conflict_tendencies=("正面斩敌"), known_skills=("剑王级剑术",), knowledge_state=("知绍罗斯死因多嫌",), relationship_tendencies=("对艾莉丝同门关照",), behavior_changes_note="受任即承，以最简语言与最快剑履职", summary="寡言忠直的兽族剑王，远征前卫的定盘星。", visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(19,)),
]

cases = [
    BehaviorCase(case_id="BC16001", character_id="E0001", phase_id="P16001", phase_name="奥尔斯帝德部下初期", volume_no=16, situation_type="召唤守护兽", context="鲁迪家，龙神授阵需补离家空缺", trigger="奥尔斯帝德授含绝对服从的召唤阵", available_information="不知召出何物，知需以伟大动物为意象", action="二度灌魔召出圣兽雷欧并当场授守护使命", verbal_response="雷欧，你的使命就是保护眼前这些家人", emotional_response="紧张后安心带点哭笑", goal_at_time="以圣兽填补离家空缺", relationship_context="鲁迪对雷欧主从，对家人为守护对象", social_context="家庭半公开仪式", immediate_outcome="雷欧汪声认主", long_term_outcome="获龙神判定家人无虞", tags=("TRUST","PROTECT","FAMILY"), evidence_refs=ev(7,8)),
    BehaviorCase(case_id="BC16002", character_id="E0001", phase_id="P16001", phase_name="奥尔斯帝德部下初期", volume_no=16, situation_type="审视可疑者", context="家门前路克突访撩艾莉丝", trigger="归家见路克倒地白眼", available_information="日记与龙神皆指路克疑为使徒", action="背入置床后诘问人神名观察茫然搔头", verbal_response="你曾听过人神这个名字吗", emotional_response="警惕与伦理犹疑", goal_at_time="判别使徒真伪", relationship_context="对路克审视对艾莉丝守护", social_context="家庭私域处置", immediate_outcome="路克否认称在龙王处亦闻人神", long_term_outcome="转密报与持续监视", tags=("SUSPICION","TRUST","NEGOTIATION"), evidence_refs=ev(10,11)),
    BehaviorCase(case_id="BC16003", character_id="E0001", phase_id="P16001", phase_name="奥尔斯帝德部下初期", volume_no=16, situation_type="密报受令", context="夏利亚郊外小屋用戒指呼唤龙神", trigger="路克求援与诅咒疑虑需定方针", available_information="人神可控三人、诅咒致亲友不信", action="详报雷欧与路克接受可控三人等判定", verbal_response="目前方针依旧是说服佩尔基乌斯对吗", emotional_response="对杀人抗拒与对规模忧虑", goal_at_time="校准助王与监控使徒", relationship_context="对龙神上下级对路克监控对象", social_context="郊外私会避诅咒", immediate_outcome="确认助王不动摇", long_term_outcome="形成助王加监控双轨", tags=("LOYALTY","AUTHORITY","NEGOTIATION"), evidence_refs=ev(12,)),
    BehaviorCase(case_id="BC16004", character_id="E0001", phase_id="P16001", phase_name="奥尔斯帝德部下初期", volume_no=16, situation_type="架桥阵营", context="空要庭园茶会僵局", trigger="爱丽儿求助气场与龙王听而不决", available_information="知迪利克可成、龙王问成王要素而爱丽儿曾无答", action="转述龙神意图有限版并提议以龙王为支点、听十三旧部", verbal_response="获得佩尔基乌斯大人的帮助才是当前重要之举", emotional_response="同情与谨慎", goal_at_time="将阵营拉回龙王支点协作", relationship_context="对爱丽儿协力对希露菲为妻同护卫", social_context="庭园半公开会议", immediate_outcome="全员专注听十三人", long_term_outcome="锁定挚友答案", tags=("NEGOTIATION","TRUST","AUTHORITY"), evidence_refs=ev(14,17)),
    BehaviorCase(case_id="BC16005", character_id="E0044", phase_id="P16002", phase_name="空要待机期", volume_no=16, situation_type="自省求助", context="被指为何独烦不求助后", trigger="佩尔基乌斯宅心仁厚论被转述", available_information="知自以为是致受限、十三旧部皆可述", action="苦笑后以伸腰拍脸切换并详述十三旧部", verbal_response="让我听听这些人个别详细经历", emotional_response="自责转振作", goal_at_time="以群体史料找王要素答案", relationship_context="对鲁迪由试探转托付", social_context="私会转任务会议", immediate_outcome="路克补旁证", long_term_outcome="锁定卡瓦尼斯线索", tags=("TRUST","FAILURE","SUCCESS"), evidence_refs=ev(17,)),
    BehaviorCase(case_id="BC16006", character_id="E0001", phase_id="P16001", phase_name="奥尔斯帝德部下初期", volume_no=16, situation_type="图书迷宫探索", context="转移至图书迷宫四公里长廊", trigger="获卡瓦尼斯方向与封面备用书", available_information="知不可毁书、魔物为使魔、年代外新内旧", action="分工静默行军休整，与贝多贝换书寻得蝶纹日记与无力神子条目", verbal_response="会让爱丽儿大人开心的东西", emotional_response="对情报被印证的安心", goal_at_time="以史料答龙王问", relationship_context="对爱丽儿为finder对希露菲前后卫默契", social_context="迷宫内静默行军", immediate_outcome="获日记爱丽儿称知道答案", long_term_outcome="晋见资本齐备", tags=("DANGER","TRUST","SUCCESS"), evidence_refs=ev(18,20,21,22)),
    BehaviorCase(case_id="BC16007", character_id="E0001", phase_id="P16001", phase_name="奥尔斯帝德部下初期", volume_no=16, situation_type="战斗掩护", context="归还书籍后史莱姆与蜗牛并发袭爱丽儿", trigger="迟缓未冻、基列奴未竟第四只、史莱姆穿侧", available_information="Frost Nova仅迟缓、岩炮弹可粉碎蜗牛", action="先迟缓群后岩炮弹粉碎蜗牛，配合换位路克补挡", verbal_response="岩炮弹", emotional_response="瞬时决断事后致歉", goal_at_time="保住爱丽儿全队脱出", relationship_context="与希露菲换位与路克并肩", social_context="限毁书战斗", immediate_outcome="蜗牛粉碎队伍安然", long_term_outcome="路克以实绩部分自证", tags=("COMBAT","PROTECT","DANGER"), evidence_refs=ev(23,)),
    BehaviorCase(case_id="BC16008", character_id="E0044", phase_id="P16002", phase_name="空要待机期", volume_no=16, situation_type="龙王晋见", context="晋见之间十二精灵环立", trigger="龙王再问成王要素", available_information="持日记悟身边有挚友", action="答挚友环绕继承无名者遗志虽觉不中意仍直言", verbal_response="身边有众多挚友", emotional_response="无畏紧绷后成就", goal_at_time="赢取龙王背书", relationship_context="对龙王问答择主", social_context="庄严公开晋见", immediate_outcome="龙王宣告助阵备转移阵", long_term_outcome="与第一王子派趋平分", tags=("AUTHORITY","SUCCESS","NEGOTIATION"), evidence_refs=ev(24,)),
    BehaviorCase(case_id="BC16009", character_id="E0001", phase_id="P16001", phase_name="奥尔斯帝德部下初期", volume_no=16, situation_type="战后复盘与管制", context="龙王助阵后报转移阵全失效", trigger="奉命启阵无响应", available_information="阵为唯一捷径或已被破坏", action="三度密报接受大流士与路克判定并约定最小化披露", verbal_response="爱丽儿不可能被操控", emotional_response="凝重与愧疚", goal_at_time="封锁情报防窃听谋陆路", relationship_context="对亲友瞒而护", social_context="私下密报", immediate_outcome="获首肯不泄意图打使徒方略", long_term_outcome="转隐蔽助王轨道", tags=("SECRET","SUSPICION","LOYALTY"), evidence_refs=ev(25,)),
    BehaviorCase(case_id="BC16010", character_id="E0001", phase_id="P16001", phase_name="奥尔斯帝德部下初期", volume_no=16, situation_type="战前筹备", context="夏利亚工房与家", trigger="远征撞生产期需强化铠与解咒", available_information="斗神铠夺意识、扎诺巴克里夫可制铠", action="以结界说辞获低耗化承诺并比试光之太刀十战九败", verbal_response="奥尔斯帝德受结界保护致我落败", emotional_response="敬畏与感动落泪", goal_at_time="提升远征生存率兼顾家庭", relationship_context="对友谎而护对妻比试而敬", social_context="工房饮酒与女子会并行", immediate_outcome="克里夫应低耗化", long_term_outcome="八人五马一车启程", tags=("FRIENDSHIP","FAMILY","TRAINING"), evidence_refs=ev(26,)),
    BehaviorCase(case_id="BC16011", character_id="E0045", phase_id="P16006", phase_name="宫廷护卫期", volume_no=16, situation_type="临敌护主", context="迷宫混战史莱姆穿侧", trigger="鲁迪锁定蜗牛爱丽儿空档", available_information="自忖控力难免毁书", action="转身护于爱丽儿身前以身挡史莱姆", verbal_response="无声挡敌", emotional_response="紧张转笃定", goal_at_time="以身证护卫价值", relationship_context="对爱丽儿护卫对鲁迪并肩", social_context="小队协同", immediate_outcome="爱丽儿无伤", long_term_outcome="获鲁迪结果还不错评价", tags=("PROTECT","LOYALTY","COMBAT"), evidence_refs=ev(23,)),
    BehaviorCase(case_id="BC16012", character_id="E0022", phase_id="P16007", phase_name="剑王护卫期", volume_no=16, situation_type="受任护卫", context="受鲁迪引荐为爱丽儿拍火花", trigger="拍掉火花受任", available_information="绍罗斯死因多嫌背景", action="简答叫我基列奴后协防迟缓群与蜗牛战", verbal_response="叫我基列奴就好", emotional_response="平淡忠实", goal_at_time="以剑王之力护主", relationship_context="对爱丽儿护卫对鲁迪协作", social_context="晋见与迷宫护卫位", immediate_outcome="礼成协防有效", long_term_outcome="成远征前卫核心", tags=("LOYALTY","PROTECT","COMBAT"), evidence_refs=ev(19,23)),
]

events = [
    DetailedEvent(event_id="DE16001", event_type="召唤仪式", title="圣兽雷欧召唤", timeline_event_id="T0060", time_date=None, time_precision=DatePrecision.UNKNOWN, time_note="王位任务前一个月内，家庭内", volume_no=16, location_id=None, participants=("E0001","E0136"), prerequisites=(EventPrerequisite(prerequisite_id="EP16001", prerequisite_type=EventPrerequisiteKind.STATE, ref_id=None, statement="奥尔斯帝德提供含绝对服从契约的召唤阵", evidence_refs=ev(6,)), EventPrerequisite(prerequisite_id="EP16002", prerequisite_type=EventPrerequisiteKind.PERSON_PRESENT, ref_id="E0001", statement="鲁迪在家人围观下持阵召召", evidence_refs=ev(6,))), dependencies=(), state_changes=(StateChange(change_id="SC16001", change_kind="契约建立", subject_id="E0136", before="未缔约", after="与鲁迪缔约守护家人"), StateChange(change_id="SC16002", change_kind="战力补充", subject_id="E0001", before="离家空缺无补", after="以圣兽填补护家空缺")), trigger="为填补追随龙神后离家增多空缺", actions=("家人见证启动阵法","以伟大动物为意象二度灌魔","授守护使命"), outcome="雷欧认主，龙神判家人无虞", relationship_change_ids=("RC16001",), belief_ids=("BL16001",), canon_importance=EventImportance.MAJOR, evidence_refs=ev(7,8,9)),
    DetailedEvent(event_id="DE16002", event_type="探索", title="图书迷宫与日记发现", timeline_event_id="T0061", time_date=None, time_precision=DatePrecision.UNKNOWN, time_note="协作期间转移入迷宫", volume_no=16, location_id=None, participants=("E0001","E0044","E0006","E0045","E0021","E0022","E0137"), prerequisites=(EventPrerequisite(prerequisite_id="EP16003", prerequisite_type=EventPrerequisiteKind.KNOWLEDGE, ref_id=None, statement="知卡瓦尼斯为说服龙王枢纽", evidence_refs=ev(18,)), EventPrerequisite(prerequisite_id="EP16004", prerequisite_type=EventPrerequisiteKind.PERSON_ALIVE, ref_id="E0137", statement="贝多贝为迷宫魔王好书以书换书", evidence_refs=ev(21,))), dependencies=(EventDependency(dependency_id="ED16001", dependency_type=EventDependencyKind.REQUIRES, target_event_id="T0060", statement="家庭已托圣兽方可离家"), EventDependency(dependency_id="ED16002", dependency_type=EventDependencyKind.ENABLES, target_event_id="DE16003", statement="获日记方能晋见取胜")), state_changes=(StateChange(change_id="SC16003", change_kind="情报取得", subject_id="E0044", before="无答龙王问", after="得挚友史料与日记物证"), StateChange(change_id="SC16004", change_kind="认知更新", subject_id="E0001", before="不识纹章意", after="识为迪利克家纹")), trigger="以史料说服龙王缺决定性说辞", actions=("转移入馆静默行军","与贝多贝换书","发现蝶纹日记与无力神子条目复归"), outcome="爱丽儿称知道答案获晋见资本", relationship_change_ids=("RC16002",), belief_ids=("BL16002","BL16003"), canon_importance=EventImportance.MAJOR, evidence_refs=ev(18,21,22)),
    DetailedEvent(event_id="DE16003", event_type="问答决断", title="甲龙王晋见与背书", timeline_event_id="T0062", time_date=None, time_precision=DatePrecision.UNKNOWN, time_note="迷宫归来即晋见", volume_no=16, location_id=None, participants=("E0044","E0029","E0001","E0006","E0045"), prerequisites=(EventPrerequisite(prerequisite_id="EP16005", prerequisite_type=EventPrerequisiteKind.KNOWLEDGE, ref_id=None, statement="爱丽儿持日记与挚友史料", evidence_refs=ev(22,)), EventPrerequisite(prerequisite_id="EP16006", prerequisite_type=EventPrerequisiteKind.PERSON_ALIVE, ref_id="E0029", statement="佩尔基乌斯在空要可晋见", evidence_refs=ev(24,))), dependencies=(EventDependency(dependency_id="ED16003", dependency_type=EventDependencyKind.REQUIRES, target_event_id="DE16002", statement="需先取得史料")), state_changes=(StateChange(change_id="SC16005", change_kind="阵营确立", subject_id="E0044", before="无龙王后盾", after="获龙王助阵趋平分"), StateChange(change_id="SC16006", change_kind="任务推进", subject_id="E0029", before="听而不决", after="命备转移阵赴王宫摆排场")), trigger="龙王再问成王要素", actions=("爱丽儿陈身边有众多挚友","龙王宣告助阵令备转移阵"), outcome="获决定性后盾", relationship_change_ids=("RC16003",), belief_ids=("BL16004",), canon_importance=EventImportance.MAJOR, evidence_refs=ev(24,)),
    DetailedEvent(event_id="DE16004", event_type="情报受挫", title="转移魔法阵全失效", timeline_event_id="T0063", time_date=None, time_precision=DatePrecision.UNKNOWN, time_note="晋见后即试阵", volume_no=16, location_id=None, participants=("E0044","E0001","E0006","E0045"), prerequisites=(EventPrerequisite(prerequisite_id="EP16007", prerequisite_type=EventPrerequisiteKind.STATE, ref_id=None, statement="空要存有直通阿斯拉的转移阵", evidence_refs=ev(24,)),), dependencies=(EventDependency(dependency_id="ED16004", dependency_type=EventDependencyKind.CAUSES, target_event_id="DE16003", statement="龙王命启阵后检出失效")), state_changes=(StateChange(change_id="SC16007", change_kind="通道断绝", subject_id="E0044", before="可借阵即返", after="阵全坏须谋陆路")), trigger="希尔瓦莉尔奉命启阵", actions=("往设阵处查验","报全数破坏毫无动静"), outcome="即时归国受阻须另谋路径", relationship_change_ids=(), belief_ids=("BL16005",), canon_importance=EventImportance.MAJOR, evidence_refs=ev(24,)),
    DetailedEvent(event_id="DE16005", event_type="战备", title="远征前战力与家庭安置", timeline_event_id=None, time_date=None, time_precision=DatePrecision.UNKNOWN, time_note="离夏利亚前数日", volume_no=16, location_id=None, participants=("E0001","E0021","E0022","E0006"), prerequisites=(EventPrerequisite(prerequisite_id="EP16008", prerequisite_type=EventPrerequisiteKind.PERSON_PRESENT, ref_id="E0001", statement="扎诺巴与克里夫在工房可制铠", evidence_refs=ev(26,)),), dependencies=(EventDependency(dependency_id="ED16005", dependency_type=EventDependencyKind.ENABLES, target_event_id="T0063", statement="完备铠与诅咒对策后方陆路远征")), state_changes=(StateChange(change_id="SC16008", change_kind="装备迭代", subject_id="E0001", before="魔导铠高耗诅咒未解", after="托低耗化并议茱丽版"), StateChange(change_id="SC16009", change_kind="家庭托付", subject_id="E0006", before="护卫与母职两难", after="与莉莉雅爱夏议定照看露西")), trigger="议定陆路赴阿斯拉或撞生产期", actions=("以结界说辞获低耗化承诺","与艾莉丝光之太刀比试","女子会托婴议定"), outcome="八人五马一车告别夏利亚启程", relationship_change_ids=("RC16004",), belief_ids=("BL16006",), canon_importance=EventImportance.MINOR, evidence_refs=ev(26,)),
]

beliefs = [
    Belief(belief_id="BL16001", owner_id="E0001", topic="圣兽守护力", statement="圣兽雷欧足以守护家人使离家无后顾", certainty=Confidence.EXPLICIT, belief_state=BeliefState.FACT_KNOWN, learned_from=None, learned_at_volume=16, learned_method="亲历召唤与龙神判定", is_true_in_world=True, visible_from_volume=16, visible_to_volume=None, note="龙神称已无虞雷欧立使命", evidence_refs=ev(8,9)),
    Belief(belief_id="BL16002", owner_id="E0001", topic="卡瓦尼斯王要素", statement="卡瓦尼斯之胜在身边有众多挚友并继无名者遗志", certainty=Confidence.EXPLICIT, belief_state=BeliefState.FACT_KNOWN, learned_from="E0001", learned_at_volume=16, learned_method="图书迷宫史料与贝多贝处获书", is_true_in_world=True, visible_from_volume=16, visible_to_volume=None, note="史料载七英雄与冒险者助守土", evidence_refs=ev(21,22)),
    Belief(belief_id="BL16003", owner_id="E0044", topic="成王答案", statement="挚友环绕即成王要素已掌握可答龙王", certainty=Confidence.EXPLICIT, belief_state=BeliefState.FACT_KNOWN, learned_from="E0001", learned_at_volume=16, learned_method="同阅日记并受递书", is_true_in_world=True, visible_from_volume=16, visible_to_volume=None, note="阅后称知道答案并晋见应答", evidence_refs=ev(22,)),
    Belief(belief_id="BL16004", owner_id="E0001", topic="使徒判定", statement="大流士与路克为当前可定的人神使徒", certainty=Confidence.EXPLICIT, belief_state=BeliefState.INFERRED, learned_from="E0079", learned_at_volume=16, learned_method="龙神判时间点搭话必为人神作梗", is_true_in_world=True, visible_from_volume=16, visible_to_volume=None, note="小屋会谈点名二人", evidence_refs=ev(25,)),
    Belief(belief_id="BL16005", owner_id="E0001", topic="转移阵失效", statement="阿斯拉侧转移魔法阵已被全数破坏", certainty=Confidence.EXPLICIT, belief_state=BeliefState.FACT_KNOWN, learned_from="E0079", learned_at_volume=16, learned_method="希尔瓦莉尔当面报告", is_true_in_world=True, visible_from_volume=16, visible_to_volume=None, note="命启阵后查无响应", evidence_refs=ev(24,)),
    Belief(belief_id="BL16006", owner_id="E0001", topic="诅咒应对", statement="诅咒致人对龙神判断失常，爱丽儿抗性较高", certainty=Confidence.EXPLICIT, belief_state=BeliefState.INFERRED, learned_from=None, learned_at_volume=16, learned_method="对希露菲洛琪希难信与爱丽儿宽大评对比", is_true_in_world=True, visible_from_volume=16, visible_to_volume=None, note="爱丽儿评龙神宽大", evidence_refs=ev(15,)),
]

rel_changes = [
    RelationshipChange(change_id="RC16001", source_id="E0001", target_id="E0136", dimension="契约", before="无契", trigger="以伟大动物意象二度灌魔召圣兽", after="缔结绝对服从主从确立", at_volume=16, at_date=None, evidence_refs=ev(7,8)),
    RelationshipChange(change_id="RC16002", source_id="E0001", target_id="E0044", dimension="同盟", before="协力初成缺说辞", trigger="递日记并同证挚友史料", after="成可交付晋见的同盟搭档", at_volume=16, at_date=None, evidence_refs=ev(22,)),
    RelationshipChange(change_id="RC16003", source_id="E0044", target_id="E0029", dimension="依附", before="听而不决屡问无果", trigger="以挚友环绕答案应对晋见问", after="获龙王宣告相助成其幕僚", at_volume=16, at_date=None, evidence_refs=ev(24,)),
    RelationshipChange(change_id="RC16004", source_id="E0001", target_id="E0006", dimension="默契", before="各司其职偶有信息差", trigger="迷宫前后卫瞬间换位与夜谈分工", after="达成心有灵犀协同与托付共识", at_volume=16, at_date=None, evidence_refs=ev(23,)),
]

speech_profiles = [
    SpeechProfile(profile_id="ST16001", character_id="E0001", phase_id="P16001", phase_name="奥尔斯帝德部下初期", politeness="对龙王敬语报告体，对爱丽儿协力敬语，对家人坦诚口语", sentence_length="中长句，密报时条列十次节点", address_habits="称奥尔斯帝德大人爱丽儿大人希露菲", emotion_expression="以好可怕贼笑等夸张比喻外化紧张", anger_expression="克制以叹与自省替代斥责", shy_expression="对撩汉与好感以害羞旁白带过", intimate_speech="对三妻家常夜谈体己话", stranger_speech="对外先审后问人神名", superior_speech="对龙王唯唯试探反问您知道答案吗", inferior_speech="对雷欧命令式使命语", canonical_examples=("你的使命就是保护眼前这些家人","你曾听过人神这个名字吗"), visible_from_volume=16, evidence_refs=ev(3,6,8)),
    SpeechProfile(profile_id="ST16002", character_id="E0044", phase_id="P16002", phase_name="空要待机期", politeness="晋见极端庄敬语，私话带自嘲脆弱", sentence_length="公开不徐长句，独处气若游丝短句", address_habits="称鲁迪乌斯先生佩尔基乌斯大人", emotion_expression="以茶会伸懒腰等体态转情绪", anger_expression="以威仪问答非吼喝", shy_expression="以官能小说玩笑掩紧张", intimate_speech="与希露菲路克推心置腹谈挚友", stranger_speech="对外来精灵与鲁迪端庄迎客", superior_speech="对龙王郑重直言", inferior_speech="对臣下温和鼓励", canonical_examples=("我知道答案了","身边有众多挚友"), visible_from_volume=16, evidence_refs=ev(16,22,24)),
]

quirks = [
    CharacterQuirk(quirk_id="QK16001", character_id="E0001", phase_id="P16001", phase_name="奥尔斯帝德部下初期", category="口癖", name="内心吐槽式旁白", description="将紧张以好可怕贼笑等夸张比喻外化借以自嘲降压", intensity="MEDIUM", frequency="常见", triggers=("面对龙神严肃表情","报坏消息前"), preferred_targets=("奥尔斯帝德","人神"), avoided_targets=(), behavior_patterns=("先夸张形容再切正题",), verbal_patterns=("好像要被射杀了",), boundaries=("不对爱丽儿等人当面夸张",), exceptions=("仅私下独白或对希露菲半玩笑",), start_date=None, end_date=None, visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(1,6)),
    CharacterQuirk(quirk_id="QK16002", character_id="E0044", phase_id="P16002", phase_name="空要待机期", category="仪式化动作", name="茶会伸懒腰切换术", description="自责不适合为王后以大幅拨发高举伸腰扭颈拍脸强行切换心态", intensity="MEDIUM", frequency="偶发", triggers=("被指独烦陷入自怜",), preferred_targets=(), avoided_targets=(), behavior_patterns=("先自嘲再以肢体切回专注",), verbal_patterns=("我自以为是导致受限",), boundaries=("仅亲信小圈显露",), exceptions=(), start_date=None, end_date=None, visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(16,17)),
]

prefs = [
    CharacterPreference(preference_id="PF16001", character_id="E0001", phase_id="P16001", preference_type="喜欢", target="书籍实证", description="倾向以史料图画日记物证言而非空口说服龙王或亲友", intensity="HIGH", context="王位说服与龙王问答", visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(18,22)),
    CharacterPreference(preference_id="PF16002", character_id="E0044", phase_id="P16002", preference_type="偏好", target="挚友环绕之王", description="认同继承无名士兵遗志与挚友同行之王道反感独揽", intensity="HIGH", context="与鲁迪共证卡瓦尼斯要素后", visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(22,)),
]

body_profiles = [
    BodyLanguageProfile(profile_id="BY16001", character_id="E0044", phase_id="P16002", phase_name="空要待机期", happy_signs=("晋见成功后莞尔","与路克点头默契笑"), angry_signs=(), nervous_signs=("茶会黑眼圈气若游丝语速",), embarrassed_signs=(), lying_signs=(), fear_signs=(), thinking_signs=("拨发明志前静默俯视云海",), affection_signs=("对希露菲路克鞠躬回礼",), hostility_signs=(), visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(14,16,24)),
]

personas = [
    CharacterPersona(persona_id="PN16001", character_id="E0001", phase_id="P16001", persona_type="密使", description="对龙王忠诚的密使：公开为爱丽儿协力者私下为龙神情报线，执行知情最小化", speech_style="对不同对象切敬语与密语", behavior_traits=("密报","递书","审问人神名","隐瞒而护"), visible_from_volume=16, visible_to_volume=None, evidence_refs=ev(3,25)),
]

items = [
    ItemDef(item_id="IT16001", canonical_name="迪利克日记", aliases=("蝶纹日记","蝙蝠纹章日记"), category="书籍", subcategory="日记", description="迪利克所留记其对爱丽儿与路克期许与王权观察，封面蝙蝠纹章成说服龙王关键物证", material="纸张", size="单册", weight=None, durability=None, rarity="孤本", value_information="王位争夺中无价物证", currency=None, creator="E0046", origin="图书迷宫藏本", manufacturer=None, abilities=(), effects=("佐证挚友为王要素",), requirements=(), limitations=(), first_appearance_volume=16, first_appearance_line=146512, visible_from_volume=16, evidence_refs=ev(22,)),
]

abilities = [
    AbilityProfile(ability_id="AB16001", name="守护魔兽召唤", aliases=("圣兽召唤",), ability_type=AbilityType.MAGIC, school="召唤魔法", element=None, tier="高阶", requirements=("奥尔斯帝德提供的含绝对服从契约召唤阵",), preconditions=("以最伟大动物为意象灌魔",), mana_cost_if_known="全魔力集中灌注", stamina_cost_if_known=None, range_if_known="近距阵内", duration_if_known="持续契约", effects=("召出圣兽雷欧","缔结守护使命"), limitations=("需对应阵式与意象",), counters=(), qualitative_power="足以让龙神判家人无虞", learning_method=("龙神授阵","意象灌注"), known_users=("E0001",), evidence_refs=ev(7,8)),
]

world_rules = [
    WorldRule(rule_id="WR16001", domain=WorldRuleDomain.MAGIC, statement="图书迷宫的转移魔法阵为直通阿斯拉捷径且易被全数破坏而失灵", scope="夏利亚至阿斯拉转移网络", exceptions="无捷径须改陆路", confidence=Confidence.EXPLICIT, visible_from_volume=16, evidence_refs=ev(24,)),
    WorldRule(rule_id="WR16002", domain=WorldRuleDomain.SOCIETY, statement="阿斯拉王位成王要素在龙王试炼中以身边有众多挚友并继无名者遗志为判据", scope="佩尔基乌斯对王的择主问答", exceptions="自感不中意仍可因器量而择", confidence=Confidence.EXPLICIT, visible_from_volume=16, evidence_refs=ev(22,24)),
    WorldRule(rule_id="WR16003", domain=WorldRuleDomain.MAGIC, statement="无力神子能力可无效化其他神子能力被视为极危现即诛", scope="神子体系", exceptions="已不在世仅存记载", confidence=Confidence.EXPLICIT, visible_from_volume=16, evidence_refs=ev(21,)),
]

gaps = [
    CanonGap(gap_id="GAP16001", domain="魔法", question="无力神子是否仍有存活个体可治塞妮丝诅咒", why_needed="鲁迪欲治母亲诅咒涉远征后医疗路线", searched_volumes=(16,), status=GapStatus.OPEN, possible_sources="图书迷宫更深处或龙神藏书", note="本卷仅载已不在旧闻无现存线索"),
]

batch = EnrichmentBatch(batch_id="ENRICH_V016", source_volume=16, source_unit_ids=("U0283","U0284","U0285","U0286","U0287","U0288","U0289","U0290","U0291","U0292","U0293","U0294","U0295","U0296","U0297"), schema_version="1.0.0", evidence=tuple(evidence), character_profiles=tuple(profiles), behavior_cases=tuple(cases), detailed_events=tuple(events), items=tuple(items), item_instances=(), abilities=tuple(abilities), power_comparisons=(), world_rules=tuple(world_rules), locations=(), routes=(), travel_observations=(), organizations=(), political_states=(), species=(), creatures=(), beliefs=tuple(beliefs), economic_observations=(), relationship_changes=tuple(rel_changes), speech_profiles=tuple(speech_profiles), character_quirks=tuple(quirks), character_preferences=tuple(prefs), body_language_profiles=tuple(body_profiles), character_personas=tuple(personas), canon_conflicts=(), canon_gaps=tuple(gaps))

out = pathlib.Path("data/canon_enriched/V016.json")
out.write_text(json.dumps(batch.to_json(), ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Wrote {out} ev={len(evidence)} prof={len(profiles)} cases={len(cases)} events={len(events)}")

reg = load_entity_registry(pathlib.Path("data/canon"))
doc2 = parse_source(pathlib.Path("data/raw/无职转生TXT合集.txt").read_text(encoding="utf-8"))
batches = load_enrichment_batches(pathlib.Path("data/canon_enriched"))
report = verify_enrichment(batches, doc2, reg)
print("is_clean", report.is_clean)
for e in report.errors:
    print(e.code, e.path, e.message)
pathlib.Path("data/canon_enriched/report.json").write_text(json.dumps(report.to_json(), ensure_ascii=False, indent=2), encoding="utf-8")
